project:
  type: website

website:
  title: "Felix Geo"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
    right:
      - text: "Posts"
        href: posts/

publish:
  github:
    repository: felixgeo/felixgeo
